//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReview
    {
        public int ReviewID { get; set; }
        public int ClientID { get; set; }
        public int ClubID { get; set; }
        public string ReviewText { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Club Club { get; set; }
    }
}
