//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
        private static Entities1 _context;
        public static Entities1 Getcontext()
        {
            if (_context == null) _context = new Entities1();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientReview> ClientReviews { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<ClubService> ClubServices { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GroupTraining> GroupTrainings { get; set; }
        public virtual DbSet<IndividualTraining> IndividualTrainings { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<MembershipSale> MembershipSales { get; set; }
        public virtual DbSet<ProvidedService> ProvidedServices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TrainingType> TrainingTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
